language: node.js
sudo: required
node_js: 14
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t wildanazz/docker-react .
script:
  - docker run wildanazz/docker-react CI=true npm run test