language: node.js
node_js: node
sudo: required
services:
  - docker
before_install:
  - docker build -t wildanazz/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true wildanazz/docker-react yarn run test --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-278174693937"
  path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  skip_cleanup: true