language: node.js
sudo: required
node_js: 14
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t wildanazz/docker-react .
script:
  - docker run -e CI=true wildanazz/docker-react yarn run test --coverage