# Pull official base image
FROM node:alpine

# Set working directory
WORKDIR /app

# Add '/app/node_modules/.bin' to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# Install app dependencies
COPY package.json .

RUN npm install

# Add app
COPY . .

# Start app
CMD ["yarn", "run", "start"]
